### ISSUE TITLE
AttributeError: 'SelectMultipleField' object has no attribute '_choices' in Django 1.9 (python 3.5) 

### ISSUE THREAD

**Issue by danhaggard** [kelvinwong-ca/django-select-multiple-field#10]
I'm getting the following error when submitting a form in the Django admin with the SelectMultipleField

AttributeError: 'SelectMultipleField' object has no attribute '_choices'

Seems to be caused by line 141 in select_multiple_field.models:

        if self._choices and value:
            if isinstance(value, (list, tuple)):
                bad_values = []
                for opt in value: 
                ...

It looks like the method "._choices" has been removed in django1.9 (I can't find any mention of it in the changelog though).  If I change line 141 to:

       if self.choices and value:

It seems to work fine.

**Comment by kelvinwong-ca** [comment]
This has already been fixed in master. I'll push up the new version shortly.
