### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by ZoltanOnody** [kelvinwong-ca/django-select-multiple-field#14]
I think user should be able to define what widget he wants to use and you shouldn't enforce him to use SelectMultipleField (widget). For example I need CheckboxSelectMultiple in my project.

**Comment by MaZZly** [comment]
Isn't this possible already?

In one of my projects I used the following on a `ModelForm`:
```python
    class Meta:
        model = ModelName
        widgets = {
            'multiselectfield': forms.CheckboxSelectMultiple()
        }
```

works like a charm.
